source 'https://rubygems.org'

ruby '2.7.1'

# Direct dependencies from Gemfile.lock
gem 'middleman', '~> 4.3'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets', '~> 4.1'
gem 'middleman-syntax', '~> 3.2'
gem 'nokogiri', '~> 1.11.0'
gem 'redcarpet', '~> 3.5.0'
gem 'rouge', '~> 3.21'
gem 'sass'

# Fix for CVE-2022-44572
gem 'rack', '>= 2.2.6.2'

# Required for Ruby 3.0 compatibility
gem 'webrick'
